apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: long-pvc-h
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  volumeName: long-pv-h
