apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bot-scaling-ngrok-h
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ngrok-bot-deploy-h
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
  scaleUp:
    stabilizationWindowSeconds: 10s # if current > target during 10s than scale
    policies:
#      - type: Percent
#        value: 100
#        periodSeconds: 15
      - type: Pods
        value: 1
        periodSeconds: 15
    selectPolicy: Max
  scaleDown:
    stabilizationWindowSeconds: 10s # if current > target during 10s than scale
    policies:
      #      - type: Percent
      #        value: 100
      #        periodSeconds: 15
      - type: Pods
        value: 1
        periodSeconds: 15
    selectPolicy: Max
