apiVersion: v1
kind: PersistentVolume
metadata:
  name: ngrok-pv-h
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: '{{ .Values.pv_path }}'
