apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ngrok-pvc-h
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  volumeName: ngrok-pv-h
